server:
  port: 8081
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
logging:
  config: classpath:log/log4j2-dev.xml
elasticsearch:
  domain: localhost
  port: 9300
  index: blog
  type: article
